# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Inkwire' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Inkwire
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'GoogleSignIn'
  pod 'ImagePicker'
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'
  pod 'HanekeSwift', :git => 'https://github.com/Haneke/HanekeSwift.git', :branch => 'feature/swift-3'
  pod "MXParallaxHeader"
  pod 'JGProgressHUD'
  pod 'SWRevealViewController'
  pod 'BBBadgeBarButtonItem'  
  pod 'KILabel', '1.0.0'
  target 'InkwireTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InkwireUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
